// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoreApi.Data;

#nullable disable

namespace ScoreApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914041355_AddStatusToContestants")]
    partial class AddStatusToContestants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScoreApi.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdminId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("ScoreApi.Models.Contestant", b =>
                {
                    b.Property<int>("ContestantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContestantId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ContestantNumber")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ContestantId");

                    b.ToTable("Contestants");
                });

            modelBuilder.Entity("ScoreApi.Models.Criterion", b =>
                {
                    b.Property<int>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriterionId"));

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("CriterionId");

                    b.HasIndex("RoundId");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("ScoreApi.Models.Judge", b =>
                {
                    b.Property<int>("JudgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JudgeId"));

                    b.Property<string>("AssignedRound")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("JudgeNumber")
                        .HasColumnType("int");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("JudgeId");

                    b.ToTable("Judges");
                });

            modelBuilder.Entity("ScoreApi.Models.Round", b =>
                {
                    b.Property<int>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoundId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("RoundId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("ScoreApi.Models.ScoreSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("ContestantId")
                        .HasColumnType("int");

                    b.Property<int>("JudgeId")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionUuid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("SubmissionId");

                    b.HasIndex("ContestantId");

                    b.HasIndex("JudgeId");

                    b.HasIndex("RoundId");

                    b.HasIndex("SubmissionUuid")
                        .IsUnique();

                    b.ToTable("ScoreSubmissions");
                });

            modelBuilder.Entity("ScoreApi.Models.SubmissionScore", b =>
                {
                    b.Property<int>("SubmissionScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionScoreId"));

                    b.Property<int>("CriterionId")
                        .HasColumnType("int");

                    b.Property<decimal>("ScoreValue")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionScoreId");

                    b.HasIndex("CriterionId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionScores");
                });

            modelBuilder.Entity("ScoreApi.Models.Criterion", b =>
                {
                    b.HasOne("ScoreApi.Models.Round", "Round")
                        .WithMany("Criteria")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ScoreApi.Models.ScoreSubmission", b =>
                {
                    b.HasOne("ScoreApi.Models.Contestant", "Contestant")
                        .WithMany("ScoreSubmissions")
                        .HasForeignKey("ContestantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreApi.Models.Judge", "Judge")
                        .WithMany("ScoreSubmissions")
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreApi.Models.Round", "Round")
                        .WithMany("ScoreSubmissions")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Contestant");

                    b.Navigation("Judge");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ScoreApi.Models.SubmissionScore", b =>
                {
                    b.HasOne("ScoreApi.Models.Criterion", "Criterion")
                        .WithMany("SubmissionScores")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScoreApi.Models.ScoreSubmission", "Submission")
                        .WithMany("SubmissionScores")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("ScoreApi.Models.Contestant", b =>
                {
                    b.Navigation("ScoreSubmissions");
                });

            modelBuilder.Entity("ScoreApi.Models.Criterion", b =>
                {
                    b.Navigation("SubmissionScores");
                });

            modelBuilder.Entity("ScoreApi.Models.Judge", b =>
                {
                    b.Navigation("ScoreSubmissions");
                });

            modelBuilder.Entity("ScoreApi.Models.Round", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("ScoreSubmissions");
                });

            modelBuilder.Entity("ScoreApi.Models.ScoreSubmission", b =>
                {
                    b.Navigation("SubmissionScores");
                });
#pragma warning restore 612, 618
        }
    }
}
