import React, { useState, useEffect } from 'react';
import type { Judge } from '../types/judge';
import type { Round } from '../types/round';
import {
    getJudgesApi,
    createJudgeApi,
    updateJudgeApi,
    deleteJudgeApi,
} from '../services/judgeService';
import { getRoundsApi } from '../services/roundService';

export const Judges: React.FC = () => {
    const [judges, setJudges] = useState<Judge[]>([]);
    const [rounds, setRounds] = useState<Round[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    // Add form state — judge number and PIN are generated by the server
    const [name, setName] = useState('');
    const [assignedRound, setAssignedRound] = useState('');

    // Inline edit state (judge number and PIN are not editable)
    const [editingId, setEditingId] = useState<number | null>(null);
    const [editName, setEditName] = useState('');
    const [editRound, setEditRound] = useState('');

    const fetchAll = async () => {
        setLoading(true);
        setError(null);
        try {
            const [judgesData, roundsData] = await Promise.all([getJudgesApi(), getRoundsApi()]);
            setJudges(judgesData);
            setRounds(roundsData);
        } catch (err: any) {
            setError(err.message || 'Error fetching judges.');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchAll();
    }, []);

    const handleAddJudge = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!name) return;
        setError(null);

        try {
            await createJudgeApi({ fullName: name, assignedRound });
            setName('');
            setAssignedRound('');
            await fetchAll();
        } catch (err: any) {
            setError(err.message || 'Failed to add judge.');
        }
    };

    const startEdit = (j: Judge) => {
        setEditingId(j.judgeId);
        setEditName(j.fullName);
        setEditRound(j.assignedRound);
        setError(null);
    };

    const cancelEdit = () => {
        setEditingId(null);
        setError(null);
    };

    const handleSaveEdit = async (id: number) => {
        setError(null);
        try {
            await updateJudgeApi(id, { fullName: editName, assignedRound: editRound });
            setEditingId(null);
            await fetchAll();
        } catch (err: any) {
            setError(err.message || 'Failed to update judge.');
        }
    };

    const handleDelete = async (id: number) => {
        if (!window.confirm('Are you sure you want to delete this judge?')) return;
        setError(null);
        try {
            await deleteJudgeApi(id);
            await fetchAll();
        } catch (err: any) {
            setError(err.message || 'Failed to delete judge.');
        }
    };

    const roundSelect = (
        value: string,
        onChange: (v: string) => void,
        label: string
    ) => (
        <select
            value={value}
            onChange={(e) => onChange(e.target.value)}
            className="input h-7 w-40 text-xs"
            aria-label={label}
        >
            <option value="">— Unassigned —</option>
            {rounds.map((r) => (
                <option key={r.roundId} value={r.name}>
                    {r.sequence}. {r.name}
                </option>
            ))}
        </select>
    );

    return (
        <div className="space-y-6">
            <div className="page-header">
                <div>
                    <h2 className="page-title">Judges</h2>
                    <p className="page-desc">
                        Manage judge accounts and generate access PINs. Connection status appears once the live hub is wired up.
                    </p>
                </div>
            </div>

            {error && (
                <div className="alert-error" role="alert">
                    <span className="font-medium">Error:</span>
                    <span>{error}</span>
                </div>
            )}

            <form onSubmit={handleAddJudge} className="entry-form">
                <div>
                    <label htmlFor="judge-name" className="field-label">
                        Judge name <span className="text-danger">*</span>
                    </label>
                    <input
                        id="judge-name"
                        type="text"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        placeholder="e.g. Judge 4 (David)"
                        className="input w-56"
                        required
                    />
                </div>
                <div>
                    <label htmlFor="judge-round" className="field-label">Assigned round</label>
                    <select
                        id="judge-round"
                        value={assignedRound}
                        onChange={(e) => setAssignedRound(e.target.value)}
                        className="input"
                    >
                        <option value="">— Unassigned —</option>
                        {rounds.map((r) => (
                            <option key={r.roundId} value={r.name}>
                                {r.sequence}. {r.name}
                            </option>
                        ))}
                    </select>
                </div>
                <button type="submit" className="btn btn-primary">
                    Add Judge & Generate PIN
                </button>
            </form>

            <div className="overflow-x-auto">
                <table className="data-table">
                    <thead>
                        <tr>
                            <th className="w-20">Judge No.</th>
                            <th>Full Name</th>
                            <th className="w-28">Access PIN</th>
                            <th>Assigned Round</th>
                            <th className="w-32">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {loading ? (
                            <tr>
                                <td colSpan={5} className="text-center text-ink-muted">
                                    Loading judges…
                                </td>
                            </tr>
                        ) : judges.length === 0 ? (
                            <tr>
                                <td colSpan={5} className="text-center text-ink-muted">
                                    No judges added yet. Add the first one above.
                                </td>
                            </tr>
                        ) : (
                            judges.map((j) =>
                                editingId === j.judgeId ? (
                                    <tr key={j.judgeId}>
                                        <td className="num font-medium">#{j.judgeNumber}</td>
                                        <td>
                                            <input
                                                type="text"
                                                value={editName}
                                                onChange={(e) => setEditName(e.target.value)}
                                                className="input h-7 w-full max-w-56 text-xs"
                                                aria-label="Judge name"
                                                required
                                            />
                                        </td>
                                        <td className="num tracking-widest text-ink-muted">{j.pinCode}</td>
                                        <td>
                                            {roundSelect(editRound, setEditRound, 'Assigned round')}
                                        </td>
                                        <td>
                                            <div className="flex gap-1.5">
                                                <button
                                                    onClick={() => handleSaveEdit(j.judgeId)}
                                                    className="btn btn-primary h-7 px-2.5 text-xs"
                                                >
                                                    Save
                                                </button>
                                                <button onClick={cancelEdit} className="btn btn-secondary h-7 px-2.5 text-xs">
                                                    Cancel
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                ) : (
                                    <tr key={j.judgeId}>
                                        <td className="num font-medium">#{j.judgeNumber}</td>
                                        <td className="font-medium">{j.fullName}</td>
                                        <td className="num tracking-widest">{j.pinCode}</td>
                                        <td className="text-ink-secondary">{j.assignedRound || '—'}</td>
                                        <td>
                                            <div className="flex gap-1.5">
                                                <button
                                                    onClick={() => startEdit(j)}
                                                    className="btn btn-secondary h-7 px-2.5 text-xs"
                                                >
                                                    Edit
                                                </button>
                                                <button
                                                    onClick={() => handleDelete(j.judgeId)}
                                                    className="btn btn-ghost-danger"
                                                >
                                                    Delete
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                )
                            )
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
};